[project]
name = "comfyui-custom-node"
version = "0.1.0"
description = "Custom deployment node for ComfyUI"
authors = [
    { name="Deploy", email="hello@deploy.com" },
]

requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/jkuypers93/deploy-node" 
